# Generated by Django 5.1.2 on 2026-08-27 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live In Progress'), ('PAUSED', 'Paused / Half-Time'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('current_period', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('1ST_HALF', '1st Half'), ('HALF_TIME', 'Half Time'), ('2ND_HALF', '2nd Half'), ('EXTRA_TIME', 'Extra Time'), ('PENALTIES', 'Penalties')], default='NOT_STARTED', max_length=20)),
                ('timer_seconds_elapsed', models.PositiveIntegerField(default=0)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('timer_last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Short 3-letter abbreviation, e.g., FCB', max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sport', models.CharField(default='Soccer / Football', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('jersey_number', models.PositiveIntegerField()),
                ('position', models.CharField(blank=True, max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team')),
            ],
            options={
                'unique_together': {('team', 'jersey_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal Scored'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card'), ('FOUL', 'Foul'), ('SUBSTITUTION', 'Substitution'), ('VAR_DECISION', 'VAR Decision'), ('PERIOD_START', 'Period Started'), ('PERIOD_END', 'Period Ended')], max_length=30)),
                ('match_minute', models.PositiveIntegerField(default=0)),
                ('match_second', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='VarIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Goal check, Penalty check, Red card check', max_length=50)),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='Match time in seconds when incident occurred')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under VAR Review'), ('CONFIRMED', 'Decision Confirmed'), ('OVERTURNED', 'Decision Overturned')], default='PENDING', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_incidents', to='tournaments.match')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('CAM_LEFT', 'Left Side Angle'), ('CAM_CENTER', 'Main Center Angle'), ('CAM_RIGHT', 'Right Side Angle')], max_length=30)),
                ('stream_key', models.CharField(help_text='MediaMTX stream path e.g. cam1', max_length=100, unique=True)),
                ('ingest_protocol', models.CharField(default='RTMP', help_text='RTMP, RTSP, or SRT', max_length=20)),
                ('hls_url', models.URLField(blank=True, help_text='HLS stream URL from MediaMTX')),
                ('is_connected', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='tournaments.match')),
            ],
            options={
                'unique_together': {('match', 'label')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'name')},
        ),
    ]
