# Generated by Django 5.1.2 on 2026-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
