# Generated by Django 5.1.2 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_seed_tournament_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_next_match',
            field=models.BooleanField(default=False),
        ),
    ]
