# Generated by Django 5.1.2 on 2026-08-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_match_is_next_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('REGULAR', 'Regular Group/League'), ('QUARTER_FINAL', 'Quarter-Final'), ('SEMI_FINAL', 'Semi-Final'), ('FINAL', 'Final')], default='REGULAR', max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team'),
        ),
    ]
